dependency-dir: src/

include_directories:
    - fatfs/src/
    - ChibiOS_ext/os/hal/include
    - ChibiOS_ext/os/hal/ports/STM32/STM32F4xx
        
depends:
    - cmp_mem_access
    - crc
    - parameter
    - aseba_vm
    - chibios-syscalls
    - msgbus

source:
    - src/config_flash_storage.c
    - src/sensors/VL53L0X/VL53L0X.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_calibration.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_core.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_ranging.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_strings.c
    - src/sensors/VL53L0X/Api/platform/src/vl53l0x_i2c_platform.c
    - src/sensors/VL53L0X/Api/platform/src/vl53l0x_platform.c
    - src/msgbus/examples/chibios/port.c
    - src/msgbus/messagebus.c
    
tests:
    - tests/config_save_test.cpp
    - tests/flash_mock.cpp

target.arm:
    - src/panic.c
    - src/cmd.c
    - src/main.c
    - src/usbcfg.c
    - src/memory_protection.c
    - src/flash/flash.c
    - src/sensors/imu.c
    - src/sensors/mpu9250.c
    - src/sensors/proximity.c
    - src/sensors/battery_level.c
    - src/motors.c
    - fatfs/src/ff.c
    - src/fatfs_diskio.c
    - src/fatfs_syscall.c
    - src/sdcard.c
    - src/audio/audio_thread.c
    - src/i2c_bus.c
    - src/camera/po8030.c
    - src/camera/dcmi_camera.c
    - ChibiOS_ext/os/hal/src/dcmi.c
    - ChibiOS_ext/os/hal/ports/STM32/STM32F4xx/dcmi_lld.c
    - src/leds.c
    - src/utility.c
    - src/epuck1x/epuck1x-wrapper.c
    - src/epuck1x/Asercom.c
    - src/exti.c
    - src/spi_comm.c
    - src/audio/microphone.c
    - src/audio/mp45dt02_processing.c
    - ChibiOS_ext/os/hal/src/spi3_slave.c
    - ChibiOS_ext/os/hal/ports/STM32/LLD/SPIv1/spi3_slave_lld.c
    - src/ir_remote.c

templates:
    src/src.mk.jinja: src/src.mk
